// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ahegvxjfilqjcgsamjbb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFoZWd2eGpmaWxxamNnc2FtamJiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU0OTk2NzAsImV4cCI6MjA3MTA3NTY3MH0.ebSsoRI6ezUquiz_z-oKIFYIwlblppVw8PbNWwwkZY8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});